[project]
name = "cms_backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=49.0.0",
    "fastapi[standard]>=0.139.2",
    "markdown>=3.10.2",
    "pycryptodome>=3.23.0",
    "pyjwt[crypto]>=2.13.0",
    "python-multipart>=0.0.32",
]

[project.scripts]
start = "src.main:start"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "pyright>=1.1.411",
]
